### ISSUE TITLE
could found vpiArrayNet vpiArrayVar  in  uvm-ieee/dpi/uvm_hdl_vcs.c 

### ISSUE THREAD

**Issue by yzt000000** [Practical-UVM-Step-By-Step/Practical-UVM-IEEE-Edition#1]
compile Error when using vcs 2019.6

**Comment by Practical-UVM-Step-By-Step** [comment]
Hi:
I could not reproduce this error. Could you possibly tell me how you are compiling this code? Are you using VCS? if you are, can you tell me the settings of VCS_UVM_HOME and your -ntb_opts switches.  if you're using the provided Makefile, let me know if you set any overrides.

**Comment by Practical-UVM-Step-By-Step** [comment]
Also: Could you tell me which example gave you this problem? That was not in the problem statement.

**Comment by yzt000000** [comment]
> Hi: I could not reproduce this error. Could you possibly tell me how you are compiling this code? Are you using VCS? if you are, can you tell me the settings of VCS_UVM_HOME and your -ntb_opts switches. if you're using the provided Makefile, let me know if you set any overrides.

using VCS  P-2019.06-SP2_FULL64  -ntb_opts uvm-ieee, $VCS_UVM_HOME  using synopys's  etc/uvm-ieee

the Makefile is under "Practical-UVM-IEEEE-Edithion-master/IEEE_version/UVM_Quickstart/UVM_TestBench/run

**Comment by yzt000000** [comment]
![1637558306(1)](https://user-images.githubusercontent.com/20236351/142805029-f9f68ff3-ffb8-4433-a389-02dc0556d918.png)

**Comment by Practical-UVM-Step-By-Step** [comment]
hi:
Can you help me by checking your environment.  I don't see the problem. The log file was checked in for the same version of VCS a bit ago. I'll try running it again soon. 

try unsetting VCS_UVM_HOME if you use -ntb_opts uvm-ieee 

see the switches in:

https://github.com/Practical-UVM-Step-By-Step/Practical-UVM-IEEE-Edition/blob/master/IEEE_version/UVM_Quickstart/UVM_TestBench/run/vcs.log

let me know.

**Comment by yzt000000** [comment]
> hi: Can you help me by checking your environment. I don't see the problem. The log file was checked in for the same version of VCS a bit ago. I'll try running it again soon.
> 
> try unsetting VCS_UVM_HOME if you use -ntb_opts uvm-ieee
> 
> see the switches in:
> 
> https://github.com/Practical-UVM-Step-By-Step/Practical-UVM-IEEE-Edition/blob/master/IEEE_version/UVM_Quickstart/UVM_TestBench/run/vcs.log
> 
> let me know.

thanks， it seems to be due to GCC

**Comment by yzt000000** [comment]
> hi: Can you help me by checking your environment. I don't see the problem. The log file was checked in for the same version of VCS a bit ago. I'll try running it again soon.
> 
> try unsetting VCS_UVM_HOME if you use -ntb_opts uvm-ieee
> 
> see the switches in:
> 
> https://github.com/Practical-UVM-Step-By-Step/Practical-UVM-IEEE-Edition/blob/master/IEEE_version/UVM_Quickstart/UVM_TestBench/run/vcs.log
> 
> let me know.

just one different with you,  you use -m32

**Comment by Practical-UVM-Step-By-Step** [comment]
This is not a example problem, but a setup problem for your GCC and VCS setup.

I will suggest a few things:

1) make sure you are pointing at 64bit GCC. (gcc -id)
2) add -full64 to COMP_OPTS in Makefile (check by doing vcs -full64 -id to make sure your install is clean)
3) remove any variable pointing to VCS_UVM_HOME because that interferes with the VCS install. 

you may have a few other variables set in your environment that are interfering. Check those.

Let me know please.
Thanks!

**Comment by yzt000000** [comment]
> This is not a example problem, but a setup problem for your GCC and VCS setup.
> 
> I will suggest a few things:
> 
> 1. make sure you are pointing at 64bit GCC. (gcc -id)
> 2. add -full64 to COMP_OPTS in Makefile (check by doing vcs -full64 -id to make sure your install is clean)
> 3. remove any variable pointing to VCS_UVM_HOME because that interferes with the VCS install.
> 
> you may have a few other variables set in your environment that are interfering. Check those.
> 
> Let me know please. Thanks!

Very Strange！！！
my vcs /etc/uvm-ieee/dpi/uvm_hdl_vcs.c missing "#include "sv_vpi_user.h"

when I try to using the standard  uvm-ieee which is from “https://www.accellera.org/”， all case work well.

this should be an individual problem, not a general one.  

thanks very much.

**Comment by Practical-UVM-Step-By-Step** [comment]
OH yes, now that you remind me.  There was an issue with some of the patches of VCS. 
Move to the later patch than the one you have. This issue is gone.

**Comment by Practical-UVM-Step-By-Step** [comment]
It was a tool issue not a code issue btw.

**Comment by yzt000000** [comment]
> It was a tool issue not a code issue btw.
yes, thanks.
